### ISSUE TITLE
I can't click the top of the screen

### ISSUE THREAD

**Issue by AlNexus** [EnhancedJax/MIUI-Shade#3]
When I try to interact with something by clicking on the top of the display, it actually clicks on the "MIUI Shade Activator" and nothing happens. Is there any way to hide that?

**Comment by EnhancedJax** [comment]
You can disable the slide to activate option in the general settings. The shade would only activate if you drag instead of click

**Comment by AlNexus** [comment]
> You can disable the slide to activate option in the general settings. The shade would only activate if you drag instead of click

Can't believe I didn't see it. Thanks! Your plugins are amazing.
